### ISSUE TITLE
Suggestions!

### ISSUE THREAD

**Issue by Wolfkid200444** [manyDARK/LobbyCoreUI#3]
Hey Dark I have Suggestions if u wanna add them.
I wanna suggest if we can  Disable or enable feature and Add Particles.

**Comment by manyDARK** [comment]
Thanks for the information<33 I'm starting to develop.

**Comment by PocketMineDev** [comment]
Its Not him Plugin.

**Comment by PocketMineDev** [comment]
Its my Plugin he are Fake Dev...

**Comment by manyDARK** [comment]
give evidence... It's not your plugin. You do not have a lobby core plugin and there is no UI interface. Soo shut up thanks.

**Comment by manyDARK** [comment]
Fuck logic...

**Comment by PocketMineDev** [comment]
Not yours

**Comment by PocketMineDev** [comment]
I can Upload Mine Idiot.

**Comment by PocketMineDev** [comment]
So sad, it's BlawoHD and mine You stupid Fake developer

**Comment by manyDARK** [comment]
Give evidence, in Twitter.
