### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by cujowilliams123** [manyDARK/LobbyCoreUI#9]
Server thread/CRITICAL Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'LobbyCore v1.0.0': Call to a member function createSimpleForm() on null on many1337\Main
06.10 01:58:21 [Server] Server thread/CRITICAL Error: "Call to a member function createSimpleForm() on null" (EXCEPTION) in "LobbyCoreUI-master/src/many1337/Main" at line 179

and

06.10 02:01:12 [Server] Server thread/CRITICAL Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'LobbyCore v1.0.0': Call to a member function createSimpleForm() on null on many1337\Main
06.10 02:01:12 [Server] Server thread/CRITICAL Error: "Call to a member function createSimpleForm() on null" (EXCEPTION) in "LobbyCoreUI-master/src/many1337/Main" at line 118

**Comment by Zadezter** [comment]
What server software do you use?

**Comment by manyDARK** [comment]
Please download FormAPI and ProfileUI
